apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-client-pod
spec:
  containers:
  - name: rabbitmq-client
    image: rabbitmq:3-management
    command: ["bash", "-c", "while true; do sleep 3600; done"]
    env:
    - name: RABBITMQ_HOST
      value: "rabbitmq-service" # Remplacez par le nom du service RabbitMQ
    - name: RABBITMQ_PORT
      value: "5672" # Port par défaut pour RabbitMQ
    - name: RABBITMQ_USER
      value: "guest"
    - name: RABBITMQ_PASS
      value: "guest"
